- name: change mirror
  shell: sed -i.bk -e 's/jp.archive.ubuntu.com/ftp.jaist.ac.jp\/pub\/Linux/g' /etc/apt/sources.list
- name: apt update
  apt:
    update_cache: yes
- name: apt upgrade
  apt:
    upgrade: yes
- name: apt install package
  apt:
    pkg:
      - apt-transport-https
      - zsh
      - zip
      - unzip
      - jq
      - make
      - nano
      - git
      - curl
      - wget
      - netcat-openbsd
      - iputils-ping
      - p7zip-full
- name: snap install package
  shell: "snap install {{ item }}"
  with_items:
    - httpie
    - yq
